name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup pnpm
      - name: Setup pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer@latest | node
          echo "::add-path::$HOME/.pnpm/bin"
          pnpm config set store-dir ~/.pnpm-store

      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup pnpm
      - name: Setup pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer@latest | node
          echo "::add-path::$HOME/.pnpm/bin"
          pnpm config set store-dir ~/.pnpm-store

      - run: pnpm install --frozen-lockfile

      # Publish to npm
      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
